DoYouNowThese/DoYouNowThese.UI/Areas/Admin/Models/InformationContent/InformationContentCRUDModel.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DoYouNowThese.UI.Areas.Admin.Models.InformationContent
{
    public class InformationContentCRUDModel
    {
        public int InformationContentId { get; set; }
        public string Title { get; set; }
        public string Explanation { get; set; }
        public string PostImagePath { get; set; }
        public int? CategoryId { get; set; }
        public int? AuthorId { get; set; }
        public int LikeCount { get; set; }
        public string PathExtension { get; set; }

        public IFormFile InformationImage { get; set; }

        #region SelectList

        public SelectList CategoryList { get; set; }

        #endregion SelectList
    }
}

DoYouNowThese/DoYouNowThese.UI/Areas/Admin/Controllers/InformationContentController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using DoYouNowThese.CommonModel.AppUserModel;
using DoYouNowThese.CommonModel.InformationContentModel;
using DoYouNowThese.CommonModel.Infrastructure;
using DoYouNowThese.DATA.Models;
using DoYouNowThese.PROVIDER.Providers.CategoryOperation;
using DoYouNowThese.PROVIDER.Providers.InformationContentOperation;
using DoYouNowThese.UI.Areas.Admin.Models.InformationContent;
using DoYouNowThese.UI.Controllers;
using DoYouNowThese.UI.Models.Utility;
using DoYouNowThese.UI.Utility;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DoYouNowThese.UI.Areas.Admin.Controllers
{
    [Area("Admin")]
    [SessionControl]
    public class InformationContentController : BaseController
    {
        InformationContentProvider informationContentProvider;
        CategoryProvider categoryProvider;

        public IActionResult Index()
        {
            informationContentProvider = new InformationContentProvider();

            InfrastructureModel<List<InformationContentSingleDataModel>> infrastructureModelList = informationContentProvider.GetListInformationContent(SessionExtension.GetSessionUserTokeyKey(HttpContext.Session)); 
            return View(infrastructureModelList);
        }


        public IActionResult Insert()
        {
            InformationContentCRUDModel informationContentCRUDModel = new InformationContentCRUDModel();
            categoryProvider = new CategoryProvider();

            InfrastructureModel<List<Category>> infrastructerCategoryList = categoryProvider.GetCategoryList(SessionExtension.GetSessionUserTokeyKey(HttpContext.Session));

            informationContentCRUDModel.CategoryList = new SelectList(infrastructerCategoryList.ResultModel, "CategoryId", "Name");

            return View(informationContentCRUDModel);
        }

        [HttpPost]
        public JsonResult Insert(InformationContentCRUDModel informationContentCRUDModel)
        {
            Response response = new Response();
            try
            {
                informationContentProvider = new InformationContentProvider();

                AppUserModel appUserModel = SessionExtension.GetSessionUser(HttpContext.Session);

                InformationApiContentCRUDModel apiContentCRUDModel = new InformationApiContentCRUDModel()
                {
                    CategoryId = informationContentCRUDModel.CategoryId,
                    Explanation = informationContentCRUDModel.Explanation,
                    Title = informationContentCRUDModel.Title,
                    LikeCount = 0,
                    AuthorId= appUserModel.AppUser.AppUserId,
                    TokenKey=appUserModel.TokenKey
                };


                if (informationContentCRUDModel.InformationImage != null)
                {


                    byte[] data;
                    using (var ms = new MemoryStream())
                    {
                        informationContentCRUDModel.InformationImage.CopyTo(ms);
                        apiContentCRUDModel.PostImagePath = Path.GetExtension(informationContentCRUDModel.InformationImage.FileName);
                        data = ms.ToArray();
                    }

                    var fileContent = new ByteArrayContent(data);

                    apiContentCRUDModel.ImageArrayList = fileContent;

                    informationContentProvider.InsertInformationContent(apiContentCRUDModel);
                }
                response = new Response()
                {
                    Message = "success",
                    Status = true,
                };
            }
            catch (Exception ex)
            {
                response = new Response()
                {
                    Message = "Failed",
                    Status = false
                };
            }

            return Json(response);
        }
    }
}

DoYouNowThese/DoYouNowThese.UI/Areas/Admin/Views/InformationContent/Index.cshtml
@model DoYouNowThese.CommonModel.Infrastructure.InfrastructureModel<List<DoYouNowThese.CommonModel.InformationContentModel.InformationContentSingleDataModel>>
@using DoYouNowThese.CORE
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<!-- Panel Table Tools -->
<div class="panel">
    <header class="panel-heading">
        <h3 class="panel-title">Table Tools</h3>
    </header>
    <div class="panel-body">
        <table class="table table-hover dataTable table-striped w-full" id="exampleTableTools">
            <thead>
                <tr>
                    <th>
                        Başlık
                    </th>
                    <th>
                        Açıklama
                    </th>
                    <th>
                        Kategori Adı
                    </th>
                    <th>
                        Yazar Adı
                    </th>
                    <th>
                        Beğeni
                    </th>

                    <th>
                        Resim
                    </th>

                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th>
                        Başlık
                    </th>
                    <th>
                        Açıklama
                    </th>
                    <th>
                        Kategori Adı
                    </th>
                    <th>
                        Yazar Adı
                    </th>
                    <th>
                        Beğeni
                    </th>
                    <th>
                        Resim
                    </th>

                </tr>
            </tfoot>
            <tbody>
            <tbody>

                @foreach (var info in Model.ResultModel)
                {

                    <tr>
                        <td>@info.Title</td>
                         <td>@info.Explanation</td>
                        <td>@info.CategoryName</td>
                        <td>@info.AuthorFullName</td>
                        <td>@info.LikeCount</td>
                        <td>
                            <img class="avatar avatar-sm" src="@UrlHelper.InformationPhotoPath@info.ImagePath" data-toggle="tooltip"
                                   data-container="body"
                                 title="">
                        </td>
                    </tr>


                }
            </tbody>
        </table>
    </div>
</div>
<!-- End Panel Table Tools -->


 

DoYouNowThese/DoYouNowThese.UI/Areas/Admin/Views/InformationContent/Insert.cshtml
@model DoYouNowThese.UI.Areas.Admin.Models.InformationContent.InformationContentCRUDModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AjaxTagHelper
@{
    ViewData["Title"] = "Insert";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<div class="panel">
    <div class="panel-heading">
        <h3 class="panel-title">İçerik Oluştur</h3>
    </div>
    <div class="panel-body">
        <form id="InformationContentFormPost" asp-area="Admin" asp-action="Insert" asp-controller="InformationContent" autocomplete="off" data-ajax="true" data-ajax-method="post" data-ajax-complete="completed">
            <div class="form-group row form-material">
                <label class="col-md-3 form-control-label">Başlık</label>
                <div class="col-md-9">
                    @Html.TextBoxFor(s => s.Title, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group row form-material">
                <label class="col-md-3 form-control-label">İçerik</label>
                <div class="col-md-9">
                    <input type="text" class="form-control" name="standard_email" />
                    @Html.TextAreaFor(s => s.Explanation, new { @class = "form-control", rows = 5 })
                </div>
            </div>
            <div class="form-group row form-material">
                <label class="col-md-3 form-control-label">Kategori</label>
                <div class="col-md-9">
                    @Html.DropDownListFor(s => s.CategoryId, Model.CategoryList, new { @class = "form-control show-tick", data_plugin = "selectpicker" })
                </div>
            </div>

            <div class="form-group row form-material">
                <label class="col-md-3 form-control-label">Dosya</label>
                <div class="col-md-9">
                    @Html.TextBoxFor(s => s.InformationImage, new { @class = "form-control", @type = "file", data_plugin = "dropify", data_default_file = "" })

                </div>
            </div>

            <div class="text-right">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>




        </form>
    </div>
</div>



<!-- Core  -->
<script src="~/lib/swal/sweetalert2.all.js"></script>

<script src="~/AdminContent/vendor/jquery/jquery.minfd53.js?v4.0.1"></script>






<script>
    (function (document, window, $) {
        'use strict';

        var Site = window.Site;
        $(document).ready(function () {
                  Jform('#InformationContentFormPost');
            Site.run();
        });
    })(document, window, jQuery);
</script>

<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

<script>

    completed = function (xhr) {
        alert(`Hi ${xhr.Message}!`);
    };
 
 
</script>